site_name: Go Tsuruoka's webpage

# ナビゲーション設定を追加
nav:
  - Home: index.md
  - Slides:
    - CSS2024: slides/css2024.md

theme:
  name: material
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  favicon: assets/images/autoware-foundation.png
  icon:
    logo: fontawesome/solid/car
    repo: fontawesome/brands/github
  language: en
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  font:
    text: Roboto
    code: Roboto Mono
  version:
    provider: mike

extra_css:
  - assets/css/extra.css
  - https://use.fontawesome.com/releases/v5.15.4/css/all.css

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  # sitemap は MkDocs 1.6 で内蔵されているので削除
  - awesome-pages
  - exclude:
      regex:
        - ^(?!(.*/)?assets/).*\.(?!(.*\.)?md|(.*\.)?svg|(.*\.)?png|(.*\.)?gif|(.*\.)?jpg).*$
        - ^(.*/)?[^.]*$
  # autoware-interfaces.yaml が存在しない場合はコメントアウト
  # - macros:
  #     include_yaml:
  #       - autoware_interfaces: yaml/autoware-interfaces.yaml
  - mkdocs-video
  - same-dir
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - md_in_html
  - mdx_truly_sane_lists:
      nested_indent: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      # 修正: 新しい emoji 設定
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
      toc_depth: 3